name: cipherwords
channels:
  - anaconda
  - conda-forge   # needed for jupyterlab, jupyter_contrib_nbextensions, emcee
dependencies:
  - python=3.8    # conda default as of Apr 2021
  - pip           # ensures that any pip installs only modify this env
  - ipython
  - jupyter
  - jupyterlab    # needed for "jupyter lab"
  - ipykernel     # ensures that (base) nb_conda creates a kernel for this env
  - numpy
  - matplotlib
  - nltk
